
name: Lint

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install modules.
        run: yarn
      - name: Lint code.
        run: yarn lint
      - name: Prettier code.
        run: yarn prettier